controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1_s
      - joint_3_u
      - joint_5_b
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_2_l
      - joint_4_r
initial:  # Define initial robot poses per group
  - group: arm
    pose: crazy_pose