controller_list:
  - name: fake_hc10_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1_s
      - joint_2_l
      - joint_3_u
      - joint_4_r
      - joint_5_b
  - name: fake_hc10_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_6_t
  - name: fake_hc10_env_controller
    type: $(arg fake_execution_type)
    joints:
      - box_fixed
initial:  # Define initial robot poses per group
  - group: hc10_arm
    pose: home